### ISSUE TITLE
how to use my gromacs gpu woth biobb instead of conda gromacs

### ISSUE THREAD

**Issue by naveen584** [bioexcel/biobb_wf_md_setup#3]
how to use my gromacs gpu woth biobb instead of conda gromacs??????????/

**Comment by adamhospital** [comment]
Hi Naveen,

there is a parameter in the [mdrun building block](https://biobb-md.readthedocs.io/en/latest/gromacs.html#module-gromacs.mdrun
) that is called gmx_path, where you can put the path to your local installation GROMACS binary.  

`gmx_path (str) - (“gmx”) Path to the GROMACS executable binary.`

Here you have an example for using the local GROMACS installation in the last step of this tutorial (gmx_mpi should be in your PATH):

```
# Building Block Properties
prop = {
    'gmx_path': 'gmx_mpi'
}
```
```
# Create and launch bb
Mdrun(input_tpr_path=output_gppnpt_tpr, 
      output_trr_path=output_npt_trr, 
      output_gro_path=output_npt_gro, 
      output_edr_path=output_npt_edr, 
      output_log_path=output_npt_log, 
      output_cpt_path=output_npt_cpt,
      properties=prop).launch()

```

**Comment by naveen584** [comment]
@adamhospital  Thanks for quick response, i have another doubt that is after running your tuto. we will get **.trr  trajectory file**, but other than that we also get traj_comp.xtc file i would like to know that, can we use this compressed  **traj_comp.xtc** in place of  **.trr  trajectory file,** , or i ahve to generate inside  your notebook by adding .xtc input output parameter instead .trr.

 i want to use it for gromacs based analysis.

**Comment by adamhospital** [comment]
Hi Naveen,

two notes on this. 

The first one is that the tutorial is running a **MD setup process**. It generates a system ready to be used as input for a (long) MD simulation. The last step of the protein MD setup is a short, free MD simulation, included to ensure the robustness of the system. In the tutorial example, just 100ps-long simulation is run, for the sake of time. The trr and xtc files you are getting as a result are just for checking purposes, to catch any occurring issue before launching the real simulation.  

The second one is that to run a (longer) MD simulation, you just need to change the nsteps parameter of [the worfklow last step](http://mmb.irbbarcelona.org/biobb/availability/tutorials/md_setup#free), or add an additional step with the production MD simulation (grompp + mdrun building blocks). The number of steps that elapse between writing coordinates to the output trajectories xtc and trr files can be controlled with the corresponding mdp GROMACS parameters: nstxout (trr) and nstxout-compressed (xtc). Default values for these parameters are 5000 (trr) and 1000 (xtc) steps. Here you have an example of how to change these parameters in the BioExcel Building Blocks:

```# Create prop dict and inputs/outputs
output_gppmd_tpr = pdbCode+'_gppmd.tpr'
prop = {
    'mdp':{
        'type': 'free',
        'nsteps':'50000', # Number of steps to be run in the simulation
        'nstxout' : '500', # Write to TRR file every 500 steps (1ps)
        'nstxout-compressed' : '500' # Write to XTC file every 500 steps (1ps)
    }
}
```
```\# Create and launch bb
Grompp(input_gro_path=output_npt_gro, 
       input_top_zip_path=output_genion_top_zip, 
       output_tpr_path=output_gppmd_tpr, 
       input_cpt_path=output_npt_cpt, 
       properties=prop).launch()

**Comment by naveen584** [comment]
@adamhospital  thanks, i have one more doubt, that is 
how to add aqueous mixture of different 6 M GdmCl, 8.0 M urea,  and 8.0 M DMSO using bioexcel  workflow??

**Comment by adamhospital** [comment]
Hi Naveen,

I'm afraid this functionality is still not available in the biobbs library because the [gmx insert-molecules](http://manual.gromacs.org/documentation/current/onlinehelp/gmx-insert-molecules.html#gmx-insert-molecules) tool is not yet integrated as a building block. You can still try to build the system using the gromacs tool and then use the newly generated topology in your biobb workflow to run all the setup steps. You can follow the steps from the [GROMACS Mixed Solvent guide](http://manual.gromacs.org/documentation/current/how-to/topology.html#mixed-solvent). 

I'll add a new issue on the biobb_md module to integrate the gmx insert-molecules tool.

**Comment by naveen584** [comment]
@adamhospital ,
Hi think as a normal user , they need 4-5 parameter  that can be directly  edit from your bio-excel workflow, you have done great work by giving these options like:  PDB-ID, time for equilbrated the system and  MD-simulation,  rest is analysis and visualization. 

Here is important one , user who want to use bioexcel they actually want to use solvant mixture like DMSO,GDMCL, UREA etc directly into your notebook. so i think you have  to work on that so that bio-excel  workflow can be considered as a better option compare to using gromacs in a normal way.

Thanks.

**Comment by adamhospital** [comment]
Hi Naveen, thanks for your comment!

The BioExcel building blocks library has been never thought to be a competitor (or better option) to other tools (e.g. GROMACS), but a wrapper library offering interoperability to many different biomolecular simulation tools: chemoinformatics, docking, free energy, modelling, etc. That said, of course we are working on increasing the compatibility with more GROMACS tools, including the gmx insert-molecules. 

Thanks for your interest in our library!

**Comment by naveen584** [comment]
@adamhospital  Thanks
